### ISSUE TITLE
dist should accept only NonEmptyList

### ISSUE THREAD

**Issue by matthewleon** [paf31/purescript-distributions#1]
I am unable to see how an empty distribution makes any sense.

I propose to change the type of the exported `dist` constructor:

`dist :: forall p a. NonEmptyList (Tuple p a) -> Dist p a`

**Comment by matthewleon** [comment]
(might also be worth looking into accepting arbitrary non-empty collections)

**Comment by matthewleon** [comment]
(I see that doing this would pose problems for implementation of the `Plus` class, but maybe that makes sense. Curious to read what you think.)

**Comment by paf31** [comment]
I think in some cases an empty distribution could make sense. Remember, these are generalized distributions, not just probability distributions. What's the advantage of using `NonEmpty`?

**Comment by matthewleon** [comment]
I was thinking of this in terms of probability distributions, in which case `NonEmpty` would make certain operations a bit easier... But not that much. You're totally right.
